#!/bin/bash

DIRS=()

cat /tmp/edurange-roguelike/motd/f1_message.txt > /etc/motd

for FILE in /home/*; do
	if [[ -d $FILE ]]; then 
		DIRS+=( "$FILE" )
		echo $FILE
	fi
done

for studentDIR in "${DIRS[@]}"; do
	RAND=$[RANDOM%3+1]
	player=$(basename $studentDIR)
	cp /tmp/edurange-roguelike/motd/f1_message.txt /$studentDIR/
	
	mkdir $studentDIR/Door

	case $RAND in
		1) 
			touch $studentDIR/Door/sc\"r\"oll.txt
			printf "The secret word is: \"Alhambra\" \n Type \"ssh 10.0.0.9\" to continue\n" > $studentDIR/Entrance/sc\"r\"oll.txt
			;;
		2)
			touch $studentDIR/Door/.scroll
			printf "The secret word is: \"Alhambra\" \n Type \"ssh 10.0.0.9\" to cootinue\n" > $studentDIR/Entrance/.scroll
			;;
		3)
			touch $studentDIR/Door/s\ c\ r\ o\ l\ l.txt
			printf "The secret word is: \"Alhambra\" \n Type \"ssh 10.0.0.9\" to continue\n" > $studentDIR/Entrance/s\ c\ r\ o\ l\ l.txt
			;;
		*)
			touch $studentDIR/Door/ohno.txt
			;;
	esac

	
	echo "cat f1_message.txt" >> $studentDIR/.bashrc

	if [ "$player" = "instructor" ]; then
		continue
	fi
	mkdir $studentDIR/bin
	chmod 755 $studentDIR/bin
	echo "PATH=$studentDIR/bin" >> $studentDIR/.bashrc
	echo "export PATH" >> $studentDIR/.bashrc
	
	ln -s /bin/cat $studentDIR/bin/
	ln -s /bin/su $studentDIR/bin/
        ln -s /bin/bash $studentDIR/bin/
	ln -s /bin/ls $studentDIR/bin/
	ln -s /bin/date $studentDIR/bin/
	ln -s /usr/bin/whoami $studentDIR/bin/
	ln -s /usr/bin/cut $studentDIR/bin/
	ln -s /usr/bin/ssh $studentDIR/bin/
	ln -s /usr/bin/sudo $studentDIR/bin/
	ln -s /usr/bin/vi $studentDIR/bin/
	
	chattr +i $studentDIR/.bashrc
done

