#!/bin/bash

DIRS=()

cat /tmp/edurange-roguelike/motd/nat_message.txt > /etc/motd

for FILE in /home/*; do
  if [[ -d $FILE ]]; then
    DIRS+=( "$FILE" )
    echo $FILE
  fi
done

for studentDIR in "${DIRS[@]}"; do
  player=$(basename $studentDIR)
  cp /tmp/edurange-roguelike/motd/nat_message.txt /$studentDIR/message.txt
done
