#!/bin/bash

DIRS=()

cat /tmp/edurange-roguelike/motd/message.txt >> /etc/motd

for FILE in /home/*; do
	if [[ -d $FILE ]]; then 
		DIRS+=( "$FILE" )
		echo $FILE
	fi
done

for studentDIR in "${DIRS[@]}"; do
	player=$(basename $studentDIR)
	cp /tmp/edurange-roguelike/motd/message.txt /$studentDIR/
	
	mkdir $studentDIR/Entrance
	mkdir $studentDIR/bin
	chmod 755 $studentDIR/bin
	echo "PATH=$studentDIR/bin" >> $studentDIR/.bashrc
	echo "export PATH" >> $studentDIR/.bashrc
	
	ln -s /bin/cat $studentDIR/bin/
	ln -s /bin/su $studentDIR/bin/
        ln -s /bin/bash $studentDIR/bin/
	ln -s /bin/ssh $studentDIR/bin/
	ln -s /bin/sudo $studentDIR/bin/
	ln -s /bin/vi $studentDIR/bin/
	
	chattr +i $studentDIR/.bashrc
done

