#!/bin/bash

DIRS=()

cat /tmp/edurange-roguelike/motd/message.txt >> /etc/motd

for FILE in /home/*; do
	if [[ -d $FILE ]]; then 
		DIRS+=( "$FILE" )
		echo $FILE
	fi
done

for studentDIR in "${DIRS[@]}"; do
	RAND=echo $((1 + RANDOM % 3))
	player=$(basename $studentDIR)
	cp /tmp/edurange-roguelike/motd/message.txt /$studentDIR/
	
	mkdir $studentDIR/Entrance

	case $RAND in
		1) 
			touch $studentDIR/Entrance/scroll.txt
			echo "The secret word is: \"Alhambra\" \n Type \"./stairs\" to continue" > $studentDIR/Entrance/scroll.txt
			;;
		2)
			touch $studentDIR/Entrance/.scroll
			echo "The secret word is: \"Alhambra\" \n Type \"./stairs\" to continue" > $studentDIR/Entrance/.scroll
			;;
		3)
			touch $studentDIR/Entrance/s\ c\ r\ o\ l\ l.txt
			echo "The secret word is: \"Alhambra\" \n Type \"./stairs\" to continue" > $studentDIR/Entrance/s\ c\ r\ o\ l\ l.txt
			;;
		*)
			touch $studentDIR/Entrance/ohno.txt
			;;
	esac


	if [ "$player" = "instructor" ]; then
		continue
	fi
	mkdir $studentDIR/bin
	chmod 755 $studentDIR/bin
	echo "PATH=$studentDIR/bin" >> $studentDIR/.bashrc
	echo "export PATH" >> $studentDIR/.bashrc
	
	ln -s /bin/cat $studentDIR/bin/
	ln -s /bin/su $studentDIR/bin/
        ln -s /bin/bash $studentDIR/bin/
	ln -s /bin/ls $studentDIR/bin/
	ln -s /bin/date $studentDIR/bin/
	ln -s /usr/bin/whoami $studentDIR/bin/
	ln -s /usr/bin/cut $studentDIR/bin/
	ln -s /usr/bin/ssh $studentDIR/bin/
	ln -s /usr/bin/sudo $studentDIR/bin/
	ln -s /usr/bin/vi $studentDIR/bin/
	
	chattr +i $studentDIR/.bashrc
done

